import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from "@google/genai";
import { MessageSquareText, Sparkles, AlertCircle } from 'lucide-react';

interface DataInterpretationProps {
  mlResults: any;
  dlResults: any;
  qmlResults: any;
}

const DataInterpretation: React.FC<DataInterpretationProps> = ({ mlResults, dlResults, qmlResults }) => {
  const [interpretation, setInterpretation] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const generateInterpretation = async () => {
    setLoading(true);
    setError(null);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });
      
      const prompt = `
        As a senior financial data scientist, interpret the following machine learning results for S&P 500 stock prediction.
        
        ML Results (Classical): ${JSON.stringify(mlResults)}
        DL Results (Deep Learning): ${JSON.stringify(dlResults)}
        QML Results (Quantum): ${JSON.stringify(qmlResults)}
        
        Provide a concise, professional analysis covering:
        1. Which model category is performing best and why?
        2. Are the results reliable for actual trading? (Consider accuracy levels)
        3. What are the key takeaways for a portfolio manager?
        4. One specific recommendation for improving the pipeline.
        
        Keep the tone technical yet accessible. Use bullet points.
      `;

      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
      });

      setInterpretation(response.text || 'No interpretation generated.');
    } catch (err) {
      console.error('Gemini Error:', err);
      setError('Failed to generate AI interpretation. Please ensure your API key is configured.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (mlResults && dlResults && qmlResults) {
      generateInterpretation();
    }
  }, [mlResults, dlResults, qmlResults]);

  return (
    <div className="bg-white border border-[#141414] p-8 space-y-6">
      <div className="flex justify-between items-center border-b border-[#141414]/10 pb-4">
        <div className="flex items-center gap-3">
          <Sparkles className="text-orange-500" size={24} />
          <h3 className="font-serif italic text-2xl">AI Data Interpretation</h3>
        </div>
        <button 
          onClick={generateInterpretation}
          disabled={loading}
          className="font-mono text-[10px] uppercase tracking-widest border border-[#141414] px-3 py-1 hover:bg-[#141414] hover:text-white transition-colors disabled:opacity-50"
        >
          {loading ? 'Analyzing...' : 'Refresh Analysis'}
        </button>
      </div>

      {loading ? (
        <div className="space-y-4 animate-pulse">
          <div className="h-4 bg-[#E4E3E0] w-3/4"></div>
          <div className="h-4 bg-[#E4E3E0] w-full"></div>
          <div className="h-4 bg-[#E4E3E0] w-5/6"></div>
          <div className="h-4 bg-[#E4E3E0] w-2/3"></div>
        </div>
      ) : error ? (
        <div className="flex items-center gap-3 text-red-500 font-mono text-xs bg-red-50 p-4 border border-red-200">
          <AlertCircle size={16} />
          <span>{error}</span>
        </div>
      ) : (
        <div className="prose prose-sm max-w-none font-sans text-[#141414]/80 leading-relaxed">
          <div className="whitespace-pre-wrap">
            {interpretation || 'Waiting for data to analyze...'}
          </div>
        </div>
      )}

      <div className="pt-4 flex items-center gap-2 opacity-50">
        <MessageSquareText size={14} />
        <span className="font-mono text-[9px] uppercase tracking-widest">Generated by Gemini 3 Flash</span>
      </div>
    </div>
  );
};

export default DataInterpretation;
